/**
 * Loop System Types
 *
 * This file defines the core types for the loop primitive in Shodan workflows.
 * Loops use the same interface node pattern as components, with the addition
 * of an interface-continue node for controlling iteration.
 */

import type { PortDefinition } from './io-types.js';

/**
 * Loop node data - defines a loop container
 *
 * A loop contains child nodes that execute repeatedly until
 * the interface-continue node receives `false` on its continue input.
 *
 * Child nodes use `parentId` to reference the loop (flat model, not nested).
 *
 * The loop MUST contain these child nodes (identified by parentId):
 * - Exactly one interface-input node (provides outer inputs + iteration + prev.*)
 * - Exactly one interface-output node (defines loop's output ports)
 * - Exactly one interface-continue node (controls iteration)
 */
export interface LoopNodeData {
  nodeType: 'loop';
  label: string;

  // Safety limit to prevent infinite loops
  maxIterations: number;  // Default: 10

  // I/O ports (derived from interface nodes in child nodes)
  inputs?: PortDefinition[];
  outputs?: PortDefinition[];
}

/**
 * Interface-continue node data - controls loop iteration
 *
 * This node has a single boolean input. After each iteration:
 * - If continue = true AND iteration < maxIterations: run another iteration
 * - If continue = false OR iteration >= maxIterations: stop looping
 */
export interface InterfaceContinueNodeData {
  nodeType: 'interface-continue';
  label: string;

  // Single input port (auto-generated, but can be customized)
  inputs?: PortDefinition[];  // Default: [{ name: 'continue', type: 'boolean' }]
}

/**
 * Extended interface-input node data for loops
 *
 * When used inside a loop, interface-input provides additional outputs:
 * - iteration: number (1-based, current iteration count)
 * - prev.*: previous iteration's interface-output values (null on first iteration)
 */
export interface LoopInterfaceInputExtensions {
  // These outputs are auto-generated by the loop executor:
  // - iteration: number
  // - prev.{outputName}: for each input on interface-output
}

/**
 * Default I/O for loop-related nodes
 */
export const LOOP_NODE_DEFAULTS = {
  maxIterations: 10,
};

export const INTERFACE_CONTINUE_DEFAULT_INPUTS: PortDefinition[] = [
  {
    name: 'continue',
    type: 'boolean',
    required: true,
    description: 'Whether to continue iterating (true = continue, false = stop)',
  },
];

/**
 * Validation helpers
 */
export function isLoopNodeData(data: unknown): data is LoopNodeData {
  return (
    typeof data === 'object' &&
    data !== null &&
    (data as Record<string, unknown>).nodeType === 'loop'
  );
}

export function isInterfaceContinueNodeData(data: unknown): data is InterfaceContinueNodeData {
  return (
    typeof data === 'object' &&
    data !== null &&
    (data as Record<string, unknown>).nodeType === 'interface-continue'
  );
}
