/**
 * Loop System Types
 *
 * This file defines the core types for the loop primitive in Shodan workflows.
 * Loops use a dock-based UI for iteration control, with slots for:
 * - iteration: outputs current iteration number
 * - continue: receives boolean to control looping
 * - feedback: bidirectional slots for passing data between iterations
 */

import type { PortDefinition, ValueType } from './io-types.js';

/**
 * Dock slot types
 */
export type DockSlotType = 'iteration' | 'continue' | 'feedback';

/**
 * A slot in the loop's dock bar
 *
 * Dock slots provide iteration control and feedback:
 * - iteration: Output only (●→) - provides current iteration number
 * - continue: Input only (→●) - receives boolean to control looping
 * - feedback: Bidirectional (●→ + →●) - left port outputs prev value, right port receives current
 */
export interface DockSlot {
  name: string;
  type: DockSlotType;
  valueType: ValueType;
  label?: string;
  description?: string;
}

/**
 * Default dock slots for a new loop
 */
export const DEFAULT_DOCK_SLOTS: DockSlot[] = [
  { name: 'iteration', type: 'iteration', valueType: 'number', label: 'Iteration' },
  { name: 'continue', type: 'continue', valueType: 'boolean', label: 'Continue' },
];

/**
 * Loop node data - defines a loop container
 *
 * A loop contains child nodes that execute repeatedly until
 * the continue dock slot receives `false`.
 *
 * Child nodes use `parentId` to reference the loop (flat model, not nested).
 *
 * The loop's dock bar contains slots for iteration control:
 * - iteration: outputs current iteration number (1-based)
 * - continue: receives boolean to control looping
 * - feedback slots: user-defined bidirectional slots for iteration data
 */
export interface LoopNodeData {
  nodeType: 'loop';
  label: string;

  // Safety limit to prevent infinite loops
  maxIterations: number;  // Default: 10

  // Dock slots for iteration control
  dockSlots: DockSlot[];

  // External I/O ports (for connecting to nodes outside the loop)
  inputs?: PortDefinition[];
  outputs?: PortDefinition[];
}

/**
 * Interface-continue node data - controls loop iteration
 *
 * This node has a single boolean input. After each iteration:
 * - If continue = true AND iteration < maxIterations: run another iteration
 * - If continue = false OR iteration >= maxIterations: stop looping
 */
export interface InterfaceContinueNodeData {
  nodeType: 'interface-continue';
  label: string;

  // Single input port (auto-generated, but can be customized)
  inputs?: PortDefinition[];  // Default: [{ name: 'continue', type: 'boolean' }]
}

/**
 * Extended interface-input node data for loops
 *
 * When used inside a loop, interface-input provides additional outputs:
 * - iteration: number (1-based, current iteration count)
 * - prev.*: previous iteration's interface-output values (null on first iteration)
 */
export interface LoopInterfaceInputExtensions {
  // These outputs are auto-generated by the loop executor:
  // - iteration: number
  // - prev.{outputName}: for each input on interface-output
}

/**
 * Default I/O for loop-related nodes
 */
export const LOOP_NODE_DEFAULTS = {
  maxIterations: 10,
};

export const INTERFACE_CONTINUE_DEFAULT_INPUTS: PortDefinition[] = [
  {
    name: 'continue',
    type: 'boolean',
    required: true,
    description: 'Whether to continue iterating (true = continue, false = stop)',
  },
];

/**
 * Validation helpers
 */
export function isLoopNodeData(data: unknown): data is LoopNodeData {
  return (
    typeof data === 'object' &&
    data !== null &&
    (data as Record<string, unknown>).nodeType === 'loop'
  );
}

export function isInterfaceContinueNodeData(data: unknown): data is InterfaceContinueNodeData {
  return (
    typeof data === 'object' &&
    data !== null &&
    (data as Record<string, unknown>).nodeType === 'interface-continue'
  );
}
